# Generated by Django 4.2.13 on 2024-07-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outlookfile',
            name='name',
        ),
        migrations.AlterField(
            model_name='outlookfile',
            name='path',
            field=models.FilePathField(path='../fake_outlook'),
        ),
    ]
