# Generated by Django 4.2.13 on 2024-07-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_outlookfile_name_alter_outlookfile_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outlookfile',
            name='is_backed_up',
        ),
        migrations.AlterField(
            model_name='outlookfile',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='outlookfile',
            name='path',
            field=models.CharField(max_length=100),
        ),
    ]
